export const routes = {
  home: "/",
  login: "/login",
  register: "/register",
  onboarding: "/onboarding",

  dashboard: "/dashboard",
  conversations: "/conversations",
  channels: "/channels",
  automations: "/automations",
  notifications: "/notifications",
  erp: "/erp",
  pos: "/pos",
  posOrders: "/pos/orders",
  posInvoices: "/pos/invoices",
  posPayments: "/pos/payments",
  reports: "/reports",
  billing: "/billing",
  settings: "/settings",
  basicProducts: "/basic/products",
  basicCustomers: "/basic/customers",
  basicSales: "/basic/sales",
  basicPos: "/basic/pos",
  basicReports: "/basic/reports",

  whatsappEvolution: "/channels/whatsapp-evolution",
  whatsappCloud: "/channels/whatsapp-cloud",
  instagram: "/channels/instagram",
  messenger: "/channels/messenger",
} as const;
