export const routes = {
  home: "/",
  login: "/login",
  register: "/register",
  onboarding: "/onboarding",

  dashboard: "/dashboard",
  conversations: "/conversations",
  channels: "/channels",
  automations: "/automations",
  notifications: "/notifications",
  erp: "/erp",
  erpPurchases: "/erp/purchases",
  erpPurchasesSuppliers: "/erp/purchases/suppliers",
  erpPurchasesDocuments: "/erp/purchases/documents",
  erpPurchasesReceipts: "/erp/purchases/receipts",
  erpPurchasesPayables: "/erp/purchases/payables",
  pos: "/pos",
  posOrders: "/pos/orders",
  posInvoices: "/pos/invoices",
  posPayments: "/pos/payments",
  reports: "/reports",
  billing: "/billing",
  adminBilling: "/admin/billing",
  adminBillingUpgradeRequests: "/admin/billing/upgrade-requests",
  settings: "/settings",
  basic: "/basic",
  basicProducts: "/basic/products",
  basicCustomers: "/basic/customers",
  basicSales: "/basic/sales",
  basicPos: "/basic/pos",
  basicReports: "/basic/reports",
  basicStock: "/basic/stock",
  basicCash: "/basic/cash",

  whatsappEvolution: "/channels/whatsapp-evolution",
  whatsappCloud: "/channels/whatsapp-cloud",
  instagram: "/channels/instagram",
  messenger: "/channels/messenger",
} as const;
