"use client";

import Link from "next/link";
import { FormEvent, useState } from "react";
import { Plus, Search, X } from "lucide-react";
import { useRouter } from "next/navigation";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";

const provinces = ["Azuay","Bolívar","Cañar","Carchi","Chimborazo","Cotopaxi","El Oro","Esmeraldas","Galápagos","Guayas","Imbabura","Loja","Los Ríos","Manabí","Morona Santiago","Napo","Orellana","Pastaza","Pichincha","Santa Elena","Santo Domingo de los Tsáchilas","Sucumbíos","Tungurahua","Zamora Chinchipe"];
type Customer = Record<string, string | string[] | boolean | null> & { id: string; name: string; identificationType: string | null; additionalEmails: string[]; phoneNumbers: string[]; isActive: boolean };
type Lookup = { found: boolean; message?: string; source?: string; identification?: string; legalName?: string; tradeName?: string; taxpayerStatus?: string; taxpayerType?: string; province?: string; city?: string; economicActivity?: string; queriedAt?: string };

export function CustomerEditor({ customer }: { customer?: Customer }) {
  const router = useRouter(); const [saving, setSaving] = useState(false); const [error, setError] = useState(""); const [type, setType] = useState(customer?.identificationType ?? "RUC"); const [identification, setIdentification] = useState(String(customer?.identification ?? "")); const [emails, setEmails] = useState([String(customer?.email ?? ""), ...(customer?.additionalEmails ?? [])]); const [phones, setPhones] = useState([String(customer?.phone ?? "+593"), ...(customer?.phoneNumbers ?? [])]); const [lookup, setLookup] = useState<Lookup | null>(null);
  async function searchTaxpayer() { setError(""); const response = await fetch(`/api/sri/taxpayer-lookup?identification=${encodeURIComponent(identification)}`); const data = await response.json() as Lookup; setLookup(data); if (!response.ok && data.message) setError(data.message); }
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setSaving(true); setError(""); const form = new FormData(event.currentTarget); const string = (key: string) => String(form.get(key) ?? ""); const payload = { name: string("name"), tradeName: string("tradeName"), identificationType: type, identification, address: string("address"), country: string("country"), province: string("province"), city: string("city"), parish: string("parish"), sector: string("sector"), zone: string("zone"), customerType: string("customerType"), customerOrigin: string("customerOrigin"), groupName: string("groupName"), assignedSellerId: string("assignedSellerId"), notes: string("notes"), emails, phone: phones[0], phoneNumbers: phones.slice(1), isActive: form.get("isActive") === "on", taxpayerStatus: lookup?.taxpayerStatus, taxpayerLegalName: lookup?.legalName, taxpayerTradeName: lookup?.tradeName, taxpayerType: lookup?.taxpayerType, economicActivity: lookup?.economicActivity, taxDataSource: lookup?.source, taxDataQueriedAt: lookup?.queriedAt };
    const response = await fetch(customer ? `/api/basic/customers/${customer.id}` : "/api/basic/customers", { method: customer ? "PATCH" : "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(payload) }); const data = await response.json() as { message?: string; customer?: { id: string } }; setSaving(false); if (!response.ok) return setError(data.message ?? "No se pudo guardar."); router.push(`/facturacion/customers/${customer?.id ?? data.customer?.id}`); router.refresh(); }
  return <form onSubmit={submit} className="pb-8"><header className="sticky top-0 z-20 -mx-4 mb-5 flex items-center justify-between gap-3 border-b border-[#E4E9F0] bg-white/95 px-4 py-3 backdrop-blur sm:-mx-6 sm:px-6"><div><h1 className="text-xl font-semibold text-[#172033]">{customer ? "Editar cliente" : "Nuevo cliente"}</h1><p className="text-xs text-[#667085]">Información comercial y tributaria</p></div><div className="flex gap-2"><Button asChild variant="outline"><Link href="/facturacion/customers">Cancelar</Link></Button><Button disabled={saving} className="bg-[#1E52F1] text-white hover:bg-[#1745CE]">{saving ? "Guardando..." : "Guardar cliente"}</Button></div></header><div className="space-y-4">
    <Section title="Datos principales"><Field label="Tipo de identificación"><select value={type} onChange={(e) => setType(e.target.value)} className="h-8 w-full rounded-lg border border-[#E4E9F0] bg-white px-2 text-sm"><option value="RUC">RUC</option><option value="CEDULA">Cédula</option><option value="PASSPORT">Pasaporte</option><option value="FOREIGN_ID">Exterior</option></select></Field><Field label="Identificación"><div className="flex gap-2"><Input value={identification} onChange={(e) => { setIdentification(e.target.value); setLookup(null); }} required/><Button type="button" variant="outline" onClick={searchTaxpayer} disabled={type !== "RUC" && type !== "CEDULA"}><Search/>Buscar en SRI</Button></div></Field><Field label="Razón social / Nombres completos"><Input name="name" defaultValue={String(customer?.name ?? "")} required/></Field><Field label="Nombre comercial"><Input name="tradeName" defaultValue={String(customer?.tradeName ?? "")}/></Field><Field label="Dirección" wide><Input name="address" defaultValue={String(customer?.address ?? "")}/></Field><Field label="País"><Input name="country" defaultValue={String(customer?.country ?? "Ecuador")} readOnly={type !== "FOREIGN_ID"}/></Field></Section>
    {lookup ? <section className="rounded-xl border border-[#E4E9F0] bg-[#F8FAFD] p-4">{lookup.found ? <><p className="font-medium text-[#172033]">Datos tributarios encontrados</p><div className="mt-3 grid gap-2 text-sm sm:grid-cols-2"><Read label="Razón social SRI" value={lookup.legalName}/><Read label="Nombre comercial SRI" value={lookup.tradeName}/><Read label="Estado" value={lookup.taxpayerStatus}/><Read label="Tipo" value={lookup.taxpayerType}/><Read label="Actividad" value={lookup.economicActivity}/><Read label="Origen" value={lookup.source}/></div><p className="mt-3 text-xs text-[#667085]">Se guardarán como datos de solo lectura. Copia manualmente los valores que quieras usar en los campos principales.</p></> : <p className="text-sm text-[#667085]">{type === "CEDULA" ? "No encontramos información tributaria pública para esta identificación. Puedes completar los datos manualmente." : "No encontramos información tributaria pública para esta identificación."}</p>}</section> : null}
    <Section title="Contacto"><div className="sm:col-span-2"><ArrayFields title="Correos electrónicos" values={emails} setValues={setEmails} max={5} type="email"/></div><div className="sm:col-span-2"><ArrayFields title="Teléfonos" values={phones} setValues={setPhones} max={3} type="tel"/></div></Section>
    <Section title="Datos adicionales"><Field label="Provincia"><select name="province" defaultValue={String(customer?.province ?? "")} className="h-8 w-full rounded-lg border border-[#E4E9F0] bg-white px-2 text-sm"><option value="">Seleccionar</option>{provinces.map((province) => <option key={province}>{province}</option>)}</select></Field><Field label="Ciudad / Cantón"><Input name="city" defaultValue={String(customer?.city ?? "")}/></Field>{["parish:Parroquia","sector:Sector","zone:Zona","customerType:Tipo de cliente","customerOrigin:Origen del cliente","groupName:Grupo","assignedSellerId:Vendedor asignado"].map((item) => { const [name,label] = item.split(":"); return <Field key={name} label={label}><Input name={name} defaultValue={String(customer?.[name] ?? "")}/></Field>; })}<Field label="Observaciones" wide><textarea name="notes" defaultValue={String(customer?.notes ?? "")} className="min-h-24 w-full rounded-lg border border-[#E4E9F0] px-3 py-2 text-sm"/></Field><label className="flex items-center gap-2 text-sm"><input name="isActive" type="checkbox" defaultChecked={customer?.isActive ?? true}/>Cliente activo</label></Section>
    {error ? <p className="rounded-lg bg-red-50 p-3 text-sm text-red-700">{error}</p> : null}
  </div></form>;
}
function Section({ title, children }: { title: string; children: React.ReactNode }) { return <section className="rounded-xl border border-[#E4E9F0] bg-white p-4"><h2 className="mb-4 text-sm font-semibold uppercase tracking-wide text-[#172033]">{title}</h2><div className="grid gap-4 sm:grid-cols-2">{children}</div></section>; }
function Field({ label, children, wide }: { label: string; children: React.ReactNode; wide?: boolean }) { return <div className={`space-y-1.5 ${wide ? "sm:col-span-2" : ""}`}><Label>{label}</Label>{children}</div>; }
function Read({ label, value }: { label: string; value?: string }) { return <p><span className="text-[#667085]">{label}:</span> {value || "—"}</p>; }
function ArrayFields({ title, values, setValues, max, type }: { title: string; values: string[]; setValues: (values: string[]) => void; max: number; type: string }) { return <div><div className="mb-2 flex items-center justify-between"><div><Label>{title}</Label><p className="text-xs text-[#667085]">El primero es el principal. Máximo {max}.</p></div><Button type="button" size="sm" variant="outline" disabled={values.length >= max} onClick={() => setValues([...values, ""])}><Plus/>Agregar</Button></div><div className="space-y-2">{values.map((value,index) => <div key={index} className="flex gap-2"><Input type={type} value={value} onChange={(e) => setValues(values.map((current,i) => i === index ? e.target.value : current))}/><Button type="button" size="icon" variant="ghost" disabled={values.length === 1} onClick={() => setValues(values.filter((_,i) => i !== index))}><X/></Button></div>)}</div></div>; }
