"use client";

import Link from "next/link";
import { useMemo, useRef, useState } from "react";
import { Download, Eye, FileSpreadsheet, FileText, Pencil, Plus, Search, Upload } from "lucide-react";
import { useRouter } from "next/navigation";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";

type Customer = { id: string; name: string; tradeName: string | null; phone: string | null; email: string | null; address: string | null; identificationType: string | null; identification: string | null; customerOrigin: string | null; province: string | null; city: string | null; isActive: boolean; createdAt: string };
type Preview = { rows: Array<Record<string, string>>; valid: number; warnings: number; errors: number; issues: Array<{ row: number; level: string; message: string }> };

export function CustomerAdmin({ customers }: { customers: Customer[] }) {
  const router = useRouter(); const fileRef = useRef<HTMLInputElement>(null);
  const [query, setQuery] = useState(""); const [type, setType] = useState(""); const [status, setStatus] = useState(""); const [origin, setOrigin] = useState(""); const [province, setProvince] = useState(""); const [city, setCity] = useState(""); const [date, setDate] = useState(""); const [preview, setPreview] = useState<Preview | null>(null); const [message, setMessage] = useState("");
  const filtered = useMemo(() => customers.filter((customer) => { const needle = query.trim().toLowerCase(); return (!needle || [customer.name, customer.tradeName, customer.identification, customer.email, customer.phone].some((value) => value?.toLowerCase().includes(needle))) && (!type || customer.identificationType === type) && (!status || customer.isActive === (status === "active")) && (!origin || customer.customerOrigin === origin) && (!province || customer.province === province) && (!city || customer.city === city) && (!date || customer.createdAt.slice(0, 10) === date); }), [customers, query, type, status, origin, province, city, date]);
  const exportQuery = new URLSearchParams({ q: query, type, status, origin, province, city, date }).toString();
  async function toggle(customer: Customer) { await fetch(`/api/basic/customers/${customer.id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ isActive: !customer.isActive }) }); router.refresh(); }
  async function previewFile(file: File) { const form = new FormData(); form.set("file", file); const response = await fetch("/api/basic/customers/import/preview", { method: "POST", body: form }); const data = await response.json() as Preview & { message?: string }; if (!response.ok) return setMessage(data.message ?? "No se pudo leer el archivo."); setPreview(data); }
  async function confirmImport() { if (!preview || preview.errors) return; const response = await fetch("/api/basic/customers/import/confirm", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ rows: preview.rows }) }); const data = await response.json() as { message?: string }; setMessage(data.message ?? (response.ok ? "Importación completada." : "No se pudo importar.")); if (response.ok) { setPreview(null); router.refresh(); } }
  return <div className="space-y-4">
    <header className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><h1 className="text-2xl font-semibold text-[#172033]">Clientes</h1><p className="mt-1 text-sm text-[#667085]">Directorio comercial y tributario</p></div><div className="flex flex-wrap gap-2"><Button asChild className="bg-[#1E52F1] text-white hover:bg-[#1745CE]"><Link href="/facturacion/customers/new"><Plus />Crear cliente</Link></Button><Button variant="outline" onClick={() => fileRef.current?.click()}><Upload />Importar</Button><Button asChild variant="outline"><a href="/api/basic/customers/import/template"><Download />Formato</a></Button><input ref={fileRef} className="hidden" type="file" accept=".csv,.xlsx" onChange={(event) => event.target.files?.[0] && previewFile(event.target.files[0])} /></div></header>
    <div className="flex flex-wrap gap-2"><Button asChild variant="outline"><a href={`/api/basic/customers/export?format=pdf&${exportQuery}`}><FileText />PDF</a></Button><Button asChild variant="outline"><a href={`/api/basic/customers/export?format=xlsx&${exportQuery}`}><FileSpreadsheet />Excel</a></Button></div>
    <section className="grid gap-2 rounded-xl border border-[#E4E9F0] bg-white p-3 md:grid-cols-4 xl:grid-cols-7"><label className="relative md:col-span-2"><Search className="absolute left-3 top-2.5 size-4 text-[#667085]"/><Input className="pl-9" placeholder="Buscar..." value={query} onChange={(e) => setQuery(e.target.value)}/></label><Select label="Tipo identificación" value={type} onChange={setType} options={["RUC","CEDULA","PASSPORT","FOREIGN_ID"]}/><Select label="Estado" value={status} onChange={setStatus} options={["active","inactive"]}/><Select label="Origen" value={origin} onChange={setOrigin} options={unique(customers.map((c) => c.customerOrigin))}/><Select label="Provincia" value={province} onChange={setProvince} options={unique(customers.map((c) => c.province))}/><Select label="Ciudad" value={city} onChange={setCity} options={unique(customers.filter((c) => !province || c.province === province).map((c) => c.city))}/><Input type="date" aria-label="Fecha de registro" value={date} onChange={(e) => setDate(e.target.value)}/></section>
    {message ? <p className="text-sm text-[#667085]">{message}</p> : null}
    <div className="overflow-hidden rounded-xl border border-[#E4E9F0] bg-white"><div className="overflow-x-auto"><table className="w-full min-w-[1550px] text-left text-xs"><thead className="bg-[#F6F8FB] text-[#667085]"><tr>{["#","Tipo","Identificación","Razón social / Nombre","Nombre comercial","Origen","Email principal","Teléfono principal","Dirección","Provincia","Ciudad","Registro","Estado","Acciones"].map((label) => <th key={label} className="px-3 py-3 font-medium">{label}</th>)}</tr></thead><tbody className="divide-y divide-[#E4E9F0]">{filtered.map((customer, index) => <tr key={customer.id} className="hover:bg-[#F8FAFD]"><td className="px-3 py-3">{index + 1}</td><td className="px-3">{customer.identificationType ?? "—"}</td><td className="px-3 font-medium">{customer.identification ?? "—"}</td><td className="px-3 font-medium text-[#172033]">{customer.name}</td><td className="px-3">{customer.tradeName ?? "—"}</td><td className="px-3">{customer.customerOrigin ?? "—"}</td><td className="px-3">{customer.email ?? "—"}</td><td className="px-3">{customer.phone ?? "—"}</td><td className="max-w-48 truncate px-3">{customer.address ?? "—"}</td><td className="px-3">{customer.province ?? "—"}</td><td className="px-3">{customer.city ?? "—"}</td><td className="px-3">{new Intl.DateTimeFormat("es-EC").format(new Date(customer.createdAt))}</td><td className="px-3"><span className={customer.isActive ? "text-emerald-700" : "text-[#667085]"}>{customer.isActive ? "Activo" : "Inactivo"}</span></td><td className="px-3"><div className="flex gap-1"><Button asChild size="icon-sm" variant="ghost"><Link href={`/facturacion/customers/${customer.id}`} aria-label="Ver cliente"><Eye/></Link></Button><Button asChild size="icon-sm" variant="ghost"><Link href={`/facturacion/customers/${customer.id}?edit=1`} aria-label="Editar cliente"><Pencil/></Link></Button><Button size="sm" variant="ghost" onClick={() => toggle(customer)}>{customer.isActive ? "Desactivar" : "Activar"}</Button></div></td></tr>)}</tbody></table></div>{!filtered.length ? <p className="p-8 text-center text-sm text-[#667085]">No hay clientes que coincidan con los filtros.</p> : null}</div>
    {preview ? <div className="fixed inset-0 z-50 grid place-items-center bg-black/30 p-4"><div className="w-full max-w-2xl rounded-xl bg-white p-5 shadow-xl"><h2 className="text-lg font-semibold">Previsualizar importación</h2><div className="mt-4 grid grid-cols-3 gap-2 text-center text-sm"><p className="rounded-lg bg-emerald-50 p-3 text-emerald-700">Válidos<br/><strong>{preview.valid}</strong></p><p className="rounded-lg bg-amber-50 p-3 text-amber-700">Advertencias<br/><strong>{preview.warnings}</strong></p><p className="rounded-lg bg-red-50 p-3 text-red-700">Errores<br/><strong>{preview.errors}</strong></p></div><div className="mt-4 max-h-56 overflow-auto text-sm">{preview.issues.map((issue) => <p key={`${issue.row}-${issue.message}`} className={issue.level === "error" ? "text-red-700" : "text-amber-700"}>Fila {issue.row}: {issue.message}</p>)}</div><div className="mt-5 flex justify-end gap-2"><Button variant="outline" onClick={() => setPreview(null)}>Cancelar</Button><Button disabled={preview.errors > 0} onClick={confirmImport} className="bg-[#1E52F1] text-white">Confirmar importación</Button></div></div></div> : null}
  </div>;
}
function unique(values: Array<string | null>) { return [...new Set(values.filter((value): value is string => Boolean(value)))].sort(); }
function Select({ label, value, onChange, options }: { label: string; value: string; onChange: (value: string) => void; options: string[] }) { return <select aria-label={label} value={value} onChange={(e) => onChange(e.target.value)} className="h-8 rounded-lg border border-[#E4E9F0] bg-white px-2 text-sm"><option value="">{label}</option>{options.map((option) => <option key={option} value={option}>{option}</option>)}</select>; }
