-- CreateTable
CREATE TABLE "BusinessSettings" (
    "id" TEXT NOT NULL,
    "tenantId" TEXT NOT NULL,
    "defaultCustomerEmail" TEXT,
    "defaultQuantity" INTEGER NOT NULL DEFAULT 1,
    "salesDecimals" INTEGER NOT NULL DEFAULT 2,
    "saleDescription" TEXT,
    "enableSubsidyManagement" BOOLEAN NOT NULL DEFAULT false,
    "editSellerData" BOOLEAN NOT NULL DEFAULT false,
    "showSellerCustomers" BOOLEAN NOT NULL DEFAULT false,
    "costPriceFromNetTotal" BOOLEAN NOT NULL DEFAULT false,
    "hideObservation" BOOLEAN NOT NULL DEFAULT false,
    "hideStock" BOOLEAN NOT NULL DEFAULT false,
    "hideIva" BOOLEAN NOT NULL DEFAULT false,
    "hideDiscounts" BOOLEAN NOT NULL DEFAULT false,
    "controlStockOnSale" BOOLEAN NOT NULL DEFAULT false,
    "controlStockOnProforma" BOOLEAN NOT NULL DEFAULT false,
    "detailedInventory" BOOLEAN NOT NULL DEFAULT false,
    "enableProductCosting" BOOLEAN NOT NULL DEFAULT false,
    "autoDiscountOnSale" BOOLEAN NOT NULL DEFAULT false,
    "colBarcode" BOOLEAN NOT NULL DEFAULT true,
    "colImage" BOOLEAN NOT NULL DEFAULT true,
    "colCode" BOOLEAN NOT NULL DEFAULT true,
    "colName" BOOLEAN NOT NULL DEFAULT true,
    "colBrand" BOOLEAN NOT NULL DEFAULT true,
    "colCost" BOOLEAN NOT NULL DEFAULT true,
    "colPvpIva" BOOLEAN NOT NULL DEFAULT true,
    "colBar" BOOLEAN NOT NULL DEFAULT true,
    "colTax" BOOLEAN NOT NULL DEFAULT true,
    "colCategory" BOOLEAN NOT NULL DEFAULT true,
    "colStock" BOOLEAN NOT NULL DEFAULT true,
    "colStatus" BOOLEAN NOT NULL DEFAULT true,
    "allowDeleteDocuments" BOOLEAN NOT NULL DEFAULT false,
    "requireKeyOnSale" BOOLEAN NOT NULL DEFAULT false,
    "selectSellerOnInvoice" BOOLEAN NOT NULL DEFAULT false,
    "selectDateOnInvoice" BOOLEAN NOT NULL DEFAULT false,
    "disableManualPriceChange" BOOLEAN NOT NULL DEFAULT false,
    "showPriceWithIvaOnTicket" BOOLEAN NOT NULL DEFAULT false,
    "useBranchInfoOnPrint" BOOLEAN NOT NULL DEFAULT false,
    "includeLogoOnTicket" BOOLEAN NOT NULL DEFAULT false,
    "barcodeColumns" INTEGER NOT NULL DEFAULT 1,
    "labelShowName" BOOLEAN NOT NULL DEFAULT true,
    "labelShowCode" BOOLEAN NOT NULL DEFAULT true,
    "labelShowBrand" BOOLEAN NOT NULL DEFAULT false,
    "labelShowColor" BOOLEAN NOT NULL DEFAULT false,
    "labelShowPrice" BOOLEAN NOT NULL DEFAULT true,
    "labelShowSize" BOOLEAN NOT NULL DEFAULT false,
    "cashClosingMode" TEXT NOT NULL DEFAULT 'by_cash_register',
    "cashClosingType" TEXT NOT NULL DEFAULT 'cash_only',
    "requireCreditNoteAuth" BOOLEAN NOT NULL DEFAULT false,
    "creditNoteAuthPasswordHash" TEXT,
    "pdfBackgroundColor" TEXT NOT NULL DEFAULT '#FFFFFF',
    "pdfAccentColor" TEXT NOT NULL DEFAULT '#1a1a1a',
    "includeExtraSequential" BOOLEAN NOT NULL DEFAULT false,
    "invoiceLegend" TEXT,
    "invoiceExtraNote" TEXT,
    "proformaFormat" TEXT NOT NULL DEFAULT 'standard',
    "showResponsible" BOOLEAN NOT NULL DEFAULT false,
    "showWarehouse" BOOLEAN NOT NULL DEFAULT false,
    "showSeller" BOOLEAN NOT NULL DEFAULT false,
    "showTicketAutomatically" BOOLEAN NOT NULL DEFAULT false,
    "showResponsibilitySignatures" BOOLEAN NOT NULL DEFAULT false,
    "logoStorageKey" TEXT,
    "logoFileName" TEXT,
    "logoMimeType" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "BusinessSettings_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "BusinessSettings_tenantId_key" ON "BusinessSettings"("tenantId");

-- AddForeignKey
ALTER TABLE "BusinessSettings" ADD CONSTRAINT "BusinessSettings_tenantId_fkey" FOREIGN KEY ("tenantId") REFERENCES "Tenant"("id") ON DELETE CASCADE ON UPDATE CASCADE;
