import ExcelJS from "exceljs";
import { PDFDocument, StandardFonts, rgb } from "pdf-lib";
import { NextResponse } from "next/server";
import { getCurrentUser } from "@/lib/auth/current-user";
import { getPrismaClient } from "@/lib/db/prisma";
import { getCurrentTenant } from "@/lib/tenant/current-tenant";

export async function GET(request: Request) {
  const user = await getCurrentUser(); if (!user) return NextResponse.json({ message: "Sesión requerida." }, { status: 401 }); const tenant = await getCurrentTenant(user); const params = new URL(request.url).searchParams; const q = params.get("q")?.trim(); const type = params.get("type"); const status = params.get("status"); const origin = params.get("origin"); const province = params.get("province"); const city = params.get("city"); const date = params.get("date"); const dayStart = date ? new Date(`${date}T00:00:00`) : null; const dayEnd = dayStart ? new Date(dayStart.getTime() + 86400000) : null;
  const customers = await getPrismaClient().lightweightCustomer.findMany({ where: { tenantId: tenant.id, ...(type ? { identificationType: type as never } : {}), ...(status ? { isActive: status === "active" } : {}), ...(origin ? { customerOrigin: origin } : {}), ...(province ? { province } : {}), ...(city ? { city } : {}), ...(dayStart && dayEnd ? { createdAt: { gte: dayStart, lt: dayEnd } } : {}), ...(q ? { OR: [{ name: { contains: q, mode: "insensitive" } }, { tradeName: { contains: q, mode: "insensitive" } }, { identification: { contains: q } }, { email: { contains: q, mode: "insensitive" } }, { phone: { contains: q } }] } : {}) }, orderBy: { name: "asc" } });
  if (params.get("format") === "pdf") { const pdf = await PDFDocument.create(); const font = await pdf.embedFont(StandardFonts.Helvetica); const bold = await pdf.embedFont(StandardFonts.HelveticaBold); let page = pdf.addPage([842, 595]); let y = 555; page.drawText("Clientes", { x: 35, y, size: 16, font: bold, color: rgb(0.12, 0.32, 0.95) }); y -= 28; for (const [index, customer] of customers.entries()) { if (y < 35) { page = pdf.addPage([842, 595]); y = 555; } const line = `${index + 1}. ${customer.identificationType ?? "—"} ${customer.identification ?? "—"} | ${customer.name} | ${customer.email ?? "—"} | ${customer.phone ?? "—"} | ${customer.city ?? "—"} | ${customer.isActive ? "Activo" : "Inactivo"}`; page.drawText(line.slice(0, 145), { x: 35, y, size: 8, font }); y -= 16; } return new Response(Buffer.from(await pdf.save()), { headers: { "Content-Type": "application/pdf", "Content-Disposition": 'attachment; filename="clientes.pdf"' } }); }
  const workbook = new ExcelJS.Workbook(); const sheet = workbook.addWorksheet("Clientes"); sheet.columns = [{ header: "Tipo", key: "type", width: 18 }, { header: "Identificación", key: "identification", width: 20 }, { header: "Razón social / Nombre", key: "name", width: 34 }, { header: "Nombre comercial", key: "tradeName", width: 28 }, { header: "Origen", key: "origin", width: 18 }, { header: "Email", key: "email", width: 28 }, { header: "Teléfono", key: "phone", width: 20 }, { header: "Dirección", key: "address", width: 35 }, { header: "Provincia", key: "province", width: 18 }, { header: "Ciudad", key: "city", width: 18 }, { header: "Registro", key: "createdAt", width: 16 }, { header: "Estado", key: "status", width: 12 }]; customers.forEach((customer) => sheet.addRow({ type: customer.identificationType, identification: customer.identification, name: customer.name, tradeName: customer.tradeName, origin: customer.customerOrigin, email: customer.email, phone: customer.phone, address: customer.address, province: customer.province, city: customer.city, createdAt: customer.createdAt.toLocaleDateString("es-EC"), status: customer.isActive ? "Activo" : "Inactivo" })); sheet.getRow(1).font = { bold: true }; const buffer = await workbook.xlsx.writeBuffer(); return new Response(Buffer.from(buffer), { headers: { "Content-Type": "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", "Content-Disposition": 'attachment; filename="clientes.xlsx"' } });
}
