"use client";

import Link from "next/link";
import { useState } from "react";
import { ChevronLeft, ChevronRight, Eye, FileSearch, MoreHorizontal } from "lucide-react";

import { SriDownloadButton } from "@/components/appsolux/sri/sri-download-button";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import type { BillingDocumentListItem } from "@/lib/core/billing/billing-documents";

type FilterKey = "all" | "receipt" | "sri" | "authorized" | "pending" | "rejected" | "canceled";
const FILTERS: Array<{ key: FilterKey; label: string }> = [
  { key: "all", label: "Todos" }, { key: "receipt", label: "Recibos" }, { key: "sri", label: "Facturas SRI" },
  { key: "authorized", label: "Autorizados" }, { key: "pending", label: "Pendientes" }, { key: "rejected", label: "Rechazados" }, { key: "canceled", label: "Cancelados" },
];

function money(value: string | null) { return value === null ? "—" : `$${Number(value).toFixed(2)}`; }
function dateParts(value: string | null) { if (!value) return { date: "—", time: "" }; const date = new Date(value); return { date: date.toLocaleDateString("es-EC", { day: "2-digit", month: "short", year: "numeric" }), time: date.toLocaleTimeString("es-EC", { hour: "2-digit", minute: "2-digit" }) }; }
function sriTone(status: string | null) { if (status === "AUTHORIZED") return "bg-emerald-50 text-emerald-700"; if (status === "REJECTED" || status === "VALIDATION_ERROR") return "bg-red-50 text-red-700"; if (status === "CANCELLED") return "bg-slate-100 text-slate-500"; return "bg-amber-50 text-amber-700"; }
function paymentTone(status: string | null) { return status === "paid" ? "text-emerald-700" : status === "canceled" ? "text-slate-500" : "text-amber-700"; }

function Actions({ doc }: { doc: BillingDocumentListItem }) {
  const [open, setOpen] = useState(false);
  const primary = doc.sriDetailHref ?? doc.saleDetailHref;
  const signed = Boolean(doc.sriDocumentId && ["SIGNED", "SENT", "AUTHORIZED", "REJECTED"].includes(doc.sriStatus ?? ""));
  const canCheck = Boolean(doc.sriDetailHref && doc.accessKey && ["SIGNED", "SENT", "REJECTED"].includes(doc.sriStatus ?? ""));
  return <div className="relative flex items-center justify-end gap-1"><Button asChild={Boolean(primary)} variant="outline" size="sm" className="rounded-lg">{primary ? <Link href={primary}><Eye className="mr-1 h-4 w-4"/>Ver</Link> : <span>Ver</span>}</Button><Button variant="ghost" size="icon" onClick={() => setOpen((value) => !value)} aria-label="Más acciones"><MoreHorizontal className="h-4 w-4"/></Button>{open ? <div className="absolute right-0 top-10 z-20 w-56 rounded-xl border border-slate-200 bg-white p-1 text-left shadow-xl">
    {doc.saleDetailHref ? <Link href={doc.saleDetailHref} className="block rounded-lg px-3 py-2 text-sm hover:bg-violet-50">Ver venta</Link> : null}
    {doc.sriDetailHref ? <Link href={doc.sriDetailHref} className="block rounded-lg px-3 py-2 text-sm hover:bg-violet-50">Ver factura SRI</Link> : null}
    {!doc.sriDocumentId ? <SriDownloadButton href={`/api/basic/sales/${doc.id}/download-receipt`} label="Descargar recibo PDF" icon="receipt" className="flex w-full items-center rounded-lg px-3 py-2 text-sm hover:bg-violet-50"/> : null}
    {signed ? <SriDownloadButton href={`/api/sri/documents/${doc.sriDocumentId}/download-signed-xml`} label="Descargar XML firmado" icon="download" className="flex w-full items-center rounded-lg px-3 py-2 text-sm hover:bg-violet-50"/> : null}
    {doc.sriStatus === "AUTHORIZED" && doc.sriDocumentId ? <><SriDownloadButton href={`/api/sri/documents/${doc.sriDocumentId}/download-authorized-xml`} label="Descargar XML autorizado" icon="file-check" className="flex w-full items-center rounded-lg px-3 py-2 text-sm hover:bg-violet-50"/><SriDownloadButton href={`/api/sri/documents/${doc.sriDocumentId}/download-ride`} label="Descargar RIDE" icon="file-text" className="flex w-full items-center rounded-lg px-3 py-2 text-sm hover:bg-violet-50"/></> : null}
    {canCheck ? <Link href={doc.sriDetailHref!} className="block rounded-lg px-3 py-2 text-sm hover:bg-violet-50">Consultar autorización</Link> : null}
  </div> : null}</div>;
}

function Status({ doc }: { doc: BillingDocumentListItem }) { return <div className="space-y-1"><p className={`text-xs font-medium ${paymentTone(doc.internalStatus)}`}>Pago: {doc.internalStatusLabel ?? "No aplica"}</p>{doc.sriStatus ? <span className={`inline-flex rounded-full px-2 py-1 text-[11px] font-semibold ${sriTone(doc.sriStatus)}`}>SRI: {doc.sriStatusLabel ?? doc.sriStatus}</span> : <p className="text-xs text-slate-400">SRI: —</p>}{doc.sriStatus === "REJECTED" ? <p className="max-w-40 truncate text-[11px] text-red-600">{doc.rejectionMessage ?? "Documento devuelto por SRI"}</p> : null}</div>; }

export function BillingDocumentsList({ items, page, totalPages, totalItems, currentFilter, search, from, to, perPage, sort, basePath }: { items: BillingDocumentListItem[]; page: number; totalPages: number; totalItems: number; currentFilter: FilterKey; search: string; from: string; to: string; perPage: number; sort: "date" | "total"; basePath: string }) {
  function hrefFor(updates: Record<string,string | number | undefined>) { const params = new URLSearchParams(); const values: Record<string,string | number | undefined> = { q: search || undefined, from: from || undefined, to: to || undefined, perPage, sort, type: currentFilter, page, ...updates }; Object.entries(values).forEach(([key,value]) => { if (value !== undefined && value !== "" && value !== "all" && value !== 1 && !(key === "perPage" && value === 10) && !(key === "sort" && value === "date")) params.set(key,String(value)); }); const query = params.toString(); return query ? `${basePath}?${query}` : basePath; }
  return <div className="space-y-4"><form className="rounded-[22px] border border-slate-200 bg-slate-50/70 p-4"><div className="grid gap-3 md:grid-cols-2 xl:grid-cols-[1fr_150px_150px_100px_130px_auto]"><Input name="q" defaultValue={search} placeholder="Cliente, identificación, número, autorización o clave"/><Input name="from" type="date" defaultValue={from} aria-label="Desde"/><Input name="to" type="date" defaultValue={to} aria-label="Hasta"/><select name="perPage" defaultValue={String(perPage)} aria-label="Resultados por página" className="h-10 rounded-md border border-input bg-white px-3 text-sm"><option value="10">10 filas</option><option value="25">25 filas</option><option value="50">50 filas</option></select><select name="sort" defaultValue={sort} aria-label="Orden" className="h-10 rounded-md border border-input bg-white px-3 text-sm"><option value="date">Más recientes</option><option value="total">Mayor total</option></select><input type="hidden" name="type" value={currentFilter}/><Button className="bg-facturom-primary hover:bg-facturom-primary-soft">Buscar</Button></div><div className="mt-3 flex flex-wrap gap-1.5">{FILTERS.map((filter) => <Button key={filter.key} asChild variant={currentFilter === filter.key ? "default" : "outline"} size="sm" className={currentFilter === filter.key ? "rounded-full bg-facturom-primary hover:bg-facturom-primary-soft" : "rounded-full"}><Link href={hrefFor({ type: filter.key, page: undefined })}>{filter.label}</Link></Button>)}</div></form>
    <div className="hidden overflow-hidden rounded-[22px] border border-slate-200 bg-white md:block"><table className="w-full text-left text-sm"><thead className="border-b bg-violet-50/60 text-[11px] uppercase tracking-[.14em] text-slate-500"><tr><th className="px-5 py-4">Emisión</th><th>Documento</th><th>Cliente</th><th>Total</th><th>Estado</th><th className="pr-5 text-right">Acciones</th></tr></thead><tbody className="divide-y divide-slate-100">{items.map((doc) => { const issued = dateParts(doc.issuedAt); return <tr key={doc.id} className="transition-colors hover:bg-violet-50/35"><td className="px-5 py-4"><p className="font-medium text-slate-800">{issued.date}</p><p className="text-xs text-slate-400">{issued.time}</p></td><td><p className="font-semibold text-slate-950">{doc.sriDocumentId ? "Factura SRI" : "Recibo interno"}</p><p className="font-mono text-xs text-slate-500">{doc.displayNumber ?? `REC-${doc.id.slice(-8).toUpperCase()}`}</p>{doc.environment ? <p className="text-[11px] text-slate-400">{doc.environment === "TEST" ? "Pruebas" : "Producción"}</p> : null}</td><td><p className="max-w-56 truncate font-medium">{doc.customerName ?? "Consumidor Final"}</p><p className="text-xs text-slate-400">{doc.customerIdentification ?? (doc.customerName ? "Sin identificación" : "9999999999999")}</p></td><td className="font-mono text-base font-bold text-slate-950">{money(doc.total)}</td><td><Status doc={doc}/></td><td className="pr-5"><Actions doc={doc}/></td></tr>; })}</tbody></table></div>
    <div className="space-y-3 md:hidden">{items.map((doc) => { const issued = dateParts(doc.issuedAt); return <article key={doc.id} className="rounded-[20px] border border-slate-200 bg-white p-4 shadow-sm"><div className="flex items-start justify-between gap-3"><div><p className="text-xs font-semibold uppercase tracking-wide text-violet-700">{doc.sriDocumentId ? "Factura SRI" : "Recibo interno"}</p><p className="mt-1 font-mono text-sm font-semibold">{doc.displayNumber ?? `REC-${doc.id.slice(-8).toUpperCase()}`}</p></div><Status doc={doc}/></div><div className="my-3 border-t border-slate-100 pt-3"><p className="font-medium">{doc.customerName ?? "Consumidor Final"}</p><p className="text-xs text-slate-500">{issued.date} · {issued.time}</p></div><div className="flex items-center justify-between"><p className="font-mono text-xl font-black">{money(doc.total)}</p><Actions doc={doc}/></div></article>; })}</div>
    {items.length === 0 ? <div className="py-12 text-center text-sm text-slate-500"><FileSearch className="mx-auto mb-3 h-8 w-8 text-slate-300"/>No hay documentos que coincidan con los filtros.</div> : null}
    <div className="flex flex-col gap-3 border-t border-slate-100 pt-4 sm:flex-row sm:items-center sm:justify-between"><p className="text-xs text-slate-500">{totalItems} resultados · página {page} de {totalPages}</p><div className="flex gap-2"><Button asChild={page > 1} variant="outline" size="sm" disabled={page <= 1}>{page > 1 ? <Link href={hrefFor({ page: page - 1 })}><ChevronLeft className="h-4 w-4"/>Anterior</Link> : <span><ChevronLeft className="h-4 w-4"/>Anterior</span>}</Button><Button asChild={page < totalPages} variant="outline" size="sm" disabled={page >= totalPages}>{page < totalPages ? <Link href={hrefFor({ page: page + 1 })}>Siguiente<ChevronRight className="h-4 w-4"/></Link> : <span>Siguiente<ChevronRight className="h-4 w-4"/></span>}</Button></div></div>
  </div>;
}
